import React, { Component } from 'react';
import { Text, View, TouchableOpacity, StyleSheet } from 'react-native';

class List extends Component {
    state = {
        customers: [
            {
                id: 0,
                name: "John Smith",
                make: "Jaguar",
                model: "F-type",
                vin_number: "1GCHC29DX6E00001",
                color: "Black",
                year: "2014",
                odometer: "008946"
            },
            {
                id: 1,
                name: "Sarah Jacobs",
                make: "Lamborghini",
                model: "Veneno",
                vin_number: "1GCHC29DX6E00001",
                color: "Black",
                year: "2012",
                odometer: "002750"
            },
            {
                id: 2,
                name: "Micheal Scott",
                make: "Chrysler",
                model: "PT Cruiser",
                vin_number: "1GCHC29DX6E00001",
                color: "Burgundy",
                year: "2003",
                odometer: "075324",
            },
            {
                id: 3,
                name: "Anakin Skywalker",
                make: "Correllian",
                model: "Speeder",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2092",
                odometer: "122456",
            },
            {
                id: 4,
                name: "Kirk Keeter",
                make: "Geo",
                model: "Metro",
                vin_number: "1GCHC29DX6E00001",
                color: "Rusty Red",
                year: "1993",
                odometer: "086562",
            },
            {
                id: 5,
                name: "Alec Keeter",
                make: "McLaren",
                model: "Senna",
                vin_number: "1GCHC29DX6E00001",
                color: "white",
                year: "2019",
                odometer: "000201",
            },
            {
                id: 6,
                name: "Paddy Fitzpatrick",
                make: "Land Rover",
                model: "Defender",
                vin_number: "1GCHC29DX6E00001",
                color: "Green",
                year: "2020",
                odometer: "100324",
            },
            {
                id: 7,
                name: "Bill Merican",
                make: "Ford",
                model: "F-150",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2020",
                odometer: "000000",
            },
            {
                id: 8,
                name: "Alex Jones",
                make: "Honda",
                model: "Civic EK hatch",
                vin_number: "1GCHC29DX6E00001",
                color: "Translucent",
                year: "2020",
                odometer: "000069",
            },
            {
                id: 9,
                name: "Tom Hanks",
                make: "Porsche",
                model: "Panzerkampfwagen VI Tiger Ausf. B",
                vin_number: "1GCHC29DX6E00001",
                color: "Tan",
                year: "1944",
                odometer: "0000678",
            },
            {
                id: 10,
                name: "Erica Weiss",
                make: "BMW",
                model: "M3",
                vin_number: "1GCHC29DX6E00001",
                color: "Gold",
                year: "2018",
                odometer: "025000",
            },
            {
                id: 11,
                name: "Mel Gibson",
                make: "Toyota",
                model: "Highlander",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue w/ White",
                year: "1270",
                odometer: "061076",
            },
            {
                id: 12,
                name: "Mike Lowery",
                make: "Cadillac",
                model: "Escalade",
                vin_number: "1GCHC29DX6E00001",
                color: "Black",
                year: "2020",
                odometer: "000000",
            },
            {
                id: 13,
                name: "Tim Brown",
                make: "Honda",
                model: "Accord",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2017",
                odometer: "076821",
            },
            {
                id: 14,
                name: "Ashley Swonson",
                make: "Mercedes",
                model: "190E",
                vin_number: "1GCHC29DX6E00001",
                color: "Black",
                year: "1990",
                odometer: "110032",
            },
            {
                id: 15,
                name: "Kai Rodriguez",
                make: "Dodge",
                model: "Ram",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2019",
                odometer: "0007904",
            },
            {
                id: 16,
                name: "Brian",
                make: "Toyota",
                model: "Supra",
                vin_number: "1GCHC29DX6E00001",
                color: "Orange",
                year: "1994",
                odometer: "034777",
            },
            {
                id: 17,
                name: "Mike Reyes",
                make: "Mazda",
                model: "RX-8",
                vin_number: "1GCHC29DX6E00001",
                color: "Black",
                year: "1995",
                odometer: "120075",
            },
            {
                id: 18,
                name: "Corrine Salazar",
                make: "Jeep",
                model: "Wrangler",
                vin_number: "1GCHC29DX6E00001",
                color: "Yellow",
                year: "2004",
                odometer: "094089",
            },
            {
                id: 19,
                name: "Miguel Ibarra",
                make: "Ford",
                model: "F-350",
                vin_number: "1GCHC29DX6E00001",
                color: "White",
                year: "2014",
                odometer: "075421",
            },
            {
                id: 20,
                name: "Mark Higgins",
                make: "Alfa Romeo",
                model: "Giulia",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2019",
                odometer: "004321",
            },
            {
                id: 21,
                name: "Wendy Jones",
                make: "Ford",
                model: "Explorer",
                vin_number: "1GCHC29DX6E00001",
                color: "Gold",
                year: "2014",
                odometer: "050465",
            },
            {
                id: 22,
                name: "Jillian Reynolds",
                make: "Polaris",
                model: "RZR",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2018",
                odometer: "000565",
            },
            {
                id: 23,
                name: "Masha Grunkowski",
                make: "Toyota",
                model: "Land Cruiser",
                vin_number: "1GCHC29DX6E00001",
                color: "Grey",
                year: "1992",
                odometer: "125035",
            },
            {
                id: 24,
                name: "Garry Dangle",
                make: "Nissan",
                model: "GTR",
                vin_number: "1GCHC29DX6E00001",
                color: "Black",
                year: "2012",
                odometer: "045010",
            },
            {
                id: 25,
                name: "Veronica Townsend",
                make: "Ford",
                model: "Escape",
                vin_number: "1GCHC29DX6E00001",
                color: "Grey",
                year: "2005",
                odometer: "084096",
            },
            {
                id: 26,
                name: "Jerry Jones",
                make: "Chevrolet",
                model: "Corvette",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "1960",
                odometer: "105673",
            },
            {
                id: 27,
                name: "Marcus Johnson",
                make: "GMC",
                model: "Yukon",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2013",
                odometer: "098442",
            },
            {
                id: 28,
                name: "Cave Johnson",
                make: "Aperture Technologies",
                model: "Cave Runner",
                vin_number: "1GCHC29DX6E00001",
                color: "Lemon",
                year: "2011",
                odometer: "043021",
            },
            {
                id: 29,
                name: "Jack Spatasic",
                make: "Volvo",
                model: "C-30",
                vin_number: "1GCHC29DX6E00001",
                color: "Green",
                year: "2015",
                odometer: "015439",
            },
            {
                id: 30,
                name: "Mark Brown",
                make: "Nissan",
                model: "370Z",
                vin_number: "1GCHC29DX6E00001",
                color: "Steel",
                year: "2016",
                odometer: "056321",
            },
            {
                id: 31,
                name: "Sierra Horsely",
                make: "Chevrolet",
                model: "SS",
                vin_number: "1GCHC29DX6E00001",
                color: "Black",
                year: "2018",
                odometer: "075632",
            },
            {
                id: 32,
                name: "Jurgen Glopjisket",
                make: "BMW",
                model: "M Series",
                vin_number: "1GCHC29DX6E00001",
                color: "Yellow",
                year: "2014",
                odometer: "065421",
            },
            {
                id: 33,
                name: "Juanita Mariquilla",
                make: "Lexus",
                model: "RCF",
                vin_number: "1GCHC29DX6E00001",
                color: "White",
                year: "2016",
                odometer: "065312",
            },
            {
                id: 34,
                name: "Fred Monocle",
                make: "TVR",
                model: "Sagaris",
                vin_number: "1GCHC29DX6E00001",
                color: "Purple",
                year: "2017",
                odometer: "076832",
            },
            {
                id: 35,
                name: "Jimmy Johnson",
                make: "Ford",
                model: "Mustang GT",
                vin_number: "1GCHC29DX6E00001",
                color: "Yellow",
                year: "2003",
                odometer: "087321",
            },
            {
                id: 36,
                name: "Reed Jones",
                make: "Dodge",
                model: "Charger",
                vin_number: "1GCHC29DX6E00001",
                color: "Black",
                year: "2017",
                odometer: "034053",
            },
            {
                id: 37,
                name: "Jamie Jackson",
                make: "Toyota",
                model: "4Runner",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2010",
                odometer: "120564",
            },
            {
                id: 38,
                name: "Teressa Hughes",
                make: "Honda",
                model: "Civic Si",
                vin_number: "1GCHC29DX6E00001",
                color: "Teal",
                year: "2018",
                odometer: "011075",
            },
            {
                id: 39,
                name: "Gary Howard",
                make: "McLaren",
                model: "P1",
                vin_number: "1GCHC29DX6E00001",
                color: "Green",
                year: "2019",
                odometer: "002754",
            },
            {
                id: 40,
                name: "Howard Bow",
                make: "Ford",
                model: "GT",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2020",
                odometer: "040312",
            },
            {
                id: 41,
                name: "Hailey Furwolf",
                make: "Hyundai",
                model: "Genesis",
                vin_number: "1GCHC29DX6E00001",
                color: "Grey",
                year: "2014",
                odometer: "105423",
            },
            {
                id: 42,
                name: "Jack Johnson",
                make: "Dodge",
                model: "Durango",
                vin_number: "1GCHC29DX6E00001",
                color: "Black",
                year: "2002",
                odometer: "145092",
            },
            {
                id: 43,
                name: "Bobby Thompson",
                make: "Lexus",
                model: "ISF",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2002",
                odometer: "045765",
            },
            {
                id: 44,
                name: "Jessica Smith",
                make: "Ferrari",
                model: "F40",
                vin_number: "1GCHC29DX6E00001",
                color: "1980",
                year: "Red",
                odometer: "0076432",
            },
            {
                id: 45,
                name: "Gertrude Hilgaburg",
                make: "Opel",
                model: "Corsa",
                vin_number: "1GCHC29DX6E00001",
                color: "Brown",
                year: "2002",
                odometer: "080293",
            },
            {
                id: 46,
                name: "Jericson Jovhengis",
                make: "Subaru",
                model: "Impreza STI",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2004",
                odometer: "100423",
            },
            {
                id: 47,
                name: "Monica Zahl",
                make: "Jeep",
                model: "Grand Cherokee",
                vin_number: "1GCHC29DX6E00001",
                color: "Grey",
                year: "2017",
                odometer: "040432",
            },
            {
                id: 48,
                name: "Gerrard Bush",
                make: "Ford",
                model: "Focus RS",
                vin_number: "1GCHC29DX6E00001",
                color: "",
                year: "",
                odometer: "",
            },
            {
                id: 49,
                name: "Phyllis Jackson",
                make: "Chevrolet",
                model: "Impala",
                vin_number: "1GCHC29DX6E00001",
                color: "Tan",
                year: "2020",
                odometer: "000754",
            },
            {
                id: 50,
                name: "Tommy Thompson",
                make: "Dodge",
                model: "Challenger",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2012",
                odometer: "076502",
            },
            {
                id: 51,
                name: "Carole Fischer",
                make: "Nissan",
                model: "Rouge",
                vin_number: "1GCHC29DX6E00001",
                color: "Black",
                year: "2018",
                odometer: "076539",
            },
            {
                id: 52,
                name: "Reginald Washington",
                make: "Jeep",
                model: "Wagoneer",
                vin_number: "1GCHC29DX6E00001",
                color: "Orange",
                year: "1980",
                odometer: "130442",
            },
            {
                id: 53,
                name: "Jonas Peterson",
                make: "Chevrolet",
                model: "Nova",
                vin_number: "1GCHC29DX6E00001",
                color: "Tan",
                year: "1977",
                odometer: "130609",
            },
            {
                id: 54,
                name: "Maria Riquel",
                make: "Toyota",
                model: "Camry",
                vin_number: "1GCHC29DX6E00001",
                color: "Black",
                year: "2019",
                odometer: "030584",
            },
            {
                id: 55,
                name: "Fredrick Jones",
                make: "Dodge",
                model: "Duramax",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2016",
                odometer: "086723",
            },
            {
                id: 56,
                name: "Matilda Mathews",
                make: "Jaguar",
                model: "XJ",
                vin_number: "1GCHC29DX6E00001",
                color: "Dark Grey",
                year: "2020",
                odometer: "00026",
            },
            {
                id: 57,
                name: "Quincy Adams",
                make: "Ford",
                model: "F-150",
                vin_number: "1GCHC29DX6E00001",
                color: "White",
                year: "2017",
                odometer: "043967",
            },
            {
                id: 58,
                name: "Perry Winkle",
                make: "Dodge",
                model: "Charger",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "1970",
                odometer: "023041"
            },
            {
                id: 59,
                name: "Marcus Gilbert",
                make: "Nissan",
                model: "Altima",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2011",
                odometer: "105768",
            },
            {
                id: 60,
                name: "Barry Jordan",
                make: "Chevrolet",
                model: "Astro",
                vin_number: "1GCHC29DX6E00001",
                color: "White",
                year: "1993",
                odometer: "098643",
            },
            {
                id: 61,
                name: "Consula Griffin",
                make: "Honda",
                model: "Civic",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2002",
                odometer: "031232",
            },
            {
                id: 62,
                name: "Bronquest Heffinherfer",
                make: "Lamborghini",
                model: "Aventador",
                vin_number: "1GCHC29DX6E00001",
                color: "Purple",
                year: "2018",
                odometer: "056472",
            },
            {
                id: 63,
                name: "Jerome Piddlemeister",
                make: "Mercedes",
                model: "C30",
                vin_number: "1GCHC29DX6E00001",
                color: "Silver",
                year: "2014",
                odometer: "075631",
            },
            {
                id: 64,
                name: "Andrew Jackson",
                make: "Ford",
                model: "Mustang V6",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2014",
                odometer: "029243",
            },
            {
                id: 65,
                name: "Sasha Jepplin",
                make: "Honda",
                model: "CR-v",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2020",
                odometer: "041924",
            },
            {
                id: 66,
                name: "Hannah Gunderson",
                make: "Volvo",
                model: "XC90",
                vin_number: "1GCHC29DX6E00001",
                color: "White",
                year: "2017",
                odometer: "054722",
            },
            {
                id: 67,
                name: "Jeremy Parker",
                make: "Smart",
                model: "Smart Car",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2015",
                odometer: "097628",
            },
            {
                id: 68,
                name: "George Baker",
                make: "Telsa",
                model: "Model S",
                vin_number: "1GCHC29DX6E00001",
                color: "Slate",
                year: "2019",
                odometer: "006421",
            },
            {
                id: 69,
                name: "Mark Marble",
                make: "Chevrolet",
                model: "Silverado",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2018",
                odometer: "033632",
            },
            {
                id: 70,
                name: "Malinda Jacobs",
                make: "GMC",
                model: "Sierra",
                vin_number: "1GCHC29DX6E00001",
                color: "Pink",
                year: "2017",
                odometer: "023212",
            },
            {
                id: 71,
                name: "Jaspri Gonzalez",
                make: "Chevrolet",
                model: "Camaro",
                vin_number: "1GCHC29DX6E00001",
                color: "1969",
                year: "Orange",
                odometer: "028952",
            },
            {
                id: 72,
                name: "Cheryl Dremlin",
                make: "Acura",
                model: "TSX",
                vin_number: "1GCHC29DX6E00001",
                color: "Creme",
                year: "2004",
                odometer: "077823",
            },
            {
                id: 73,
                name: "Parker Teller",
                make: "Pagani",
                model: "Huayra",
                vin_number: "1GCHC29DX6E00001",
                color: "White",
                year: "2020",
                odometer: "000192",
            },
            {
                id: 74,
                name: "Charis Teller",
                make: "Pagani",
                model: "Zonda R",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2018",
                odometer: "001932",
            },
            {
                id: 75,
                name: "Cherno Barkov",
                make: "Lada",
                model: "4x4",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "1987",
                odometer: "109392",
            },
            {
                id: 76,
                name: "Gemma Queenstown",
                make: "Toyota",
                model: "86",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2019",
                odometer: "000000",
            },
            {
                id: 77,
                name: "Precious Marie",
                make: "Toyota",
                model: "Avalon",
                vin_number: "1GCHC29DX6E00001",
                color: "Brown",
                year: "2020",
                odometer: "002813",
            },
            {
                id: 78,
                name: "Cherry Gernie",
                make: "BMW",
                model: "550",
                vin_number: "1GCHC29DX6E00001",
                color: "Gold",
                year: "2019",
                odometer: "000172",
            },
            {
                id: 79,
                name: "Marius Danklefliegen",
                make: "Land Rover",
                model: "Discovery",
                vin_number: "1GCHC29DX6E00001",
                color: "Brown",
                year: "2012",
                odometer: "073925",
            },
            {
                id: 80,
                name: "Harold McBiggins",
                make: "Cobra",
                model: "Ace Cobra",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "1962",
                odometer: "000641",
            },
            {
                id: 81,
                name: "China Jefferson",
                make: "Aston Martin",
                model: "Vulcan",
                vin_number: "1GCHC29DX6E00001",
                color: "Bronze",
                year: "2020",
                odometer: "000000",
            },
            {
                id: 82,
                name: "Equitoria Quest",
                make: "Tesla",
                model: "Model P",
                vin_number: "1GCHC29DX6E00001",
                color: "White",
                year: "2020",
                odometer: "008213",
            },
            {
                id: 83,
                name: "Shinona Wakeeta",
                make: "GMC",
                model: "Yukon",
                vin_number: "1GCHC29DX6E00001",
                color: "Yellow",
                year: "2010",
                odometer: "092731",
            },
            {
                id: 84,
                name: "Philip Jefferspin",
                make: "Volkswagen",
                model: "Jetta",
                vin_number: "1GCHC29DX6E00001",
                color: "2014",
                year: "Blue",
                odometer: "056281",
            },
            {
                id: 85,
                name: "Madison Green",
                make: "Isuzu",
                model: "trooper",
                vin_number: "1GCHC29DX6E00001",
                color: "Multicolor",
                year: "1984",
                odometer: "000232",
            },
            {
                id: 86,
                name: "Micheal Jackson",
                make: "Mazda",
                model: "Miata",
                vin_number: "1GCHC29DX6E00001",
                color: "Red",
                year: "2005",
                odometer: "091639",
            },
            {
                id: 87,
                name: "Howard Gerber",
                make: "Subaru",
                model: "Forester",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2018",
                odometer: "017522",
            },
            {
                id: 88,
                name: "Dorian Harbleflarble",
                make: "DMC",
                model: "DeLorean",
                vin_number: "1GCHC29DX6E00001",
                color: "Silver",
                year: "2017",
                odometer: "000000",
            },
            {
                id: 89,
                name: "Kenny Lawrence",
                make: "Ford",
                model: "Fiesta",
                vin_number: "1GCHC29DX6E00001",
                color: "White",
                year: "1994",
                odometer: "089643",
            },
            {
                id: 90,
                name: "Isiah Lobertun",
                make: "GMC",
                model: "Sierra",
                vin_number: "1GCHC29DX6E00001",
                color: "Gold",
                year: "2003",
                odometer: "098236",
            },
            {
                id: 91,
                name: "Wilfred Gunter",
                make: "Porsche",
                model: "911",
                vin_number: "1GCHC29DX6E00001",
                color: "Orange",
                year: "2020",
                odometer: "000000",
            },
            {
                id: 92,
                name: "Chauncy Fillerspiller",
                make: "Chevrolet",
                model: "El Camino",
                vin_number: "1GCHC29DX6E00001",
                color: "Green",
                year: "1989",
                odometer: "093612",
            },
            {
                id: 93,
                name: "Hanslow Grownski",
                make: "Mitsubishi",
                model: "Lancer EVO",
                vin_number: "1GCHC29DX6E00001",
                color: "Grey",
                year: "2017",
                odometer: "004632",
            },
            {
                id: 94,
                name: "Henry Repeater",
                make: "Bugatti",
                model: "Chiron",
                vin_number: "1GCHC29DX6E00001",
                color: "Blue",
                year: "2020",
                odometer: "000000",
            },

        ]
    };
    alertItemName = (item) => {
        alert(item.name)
    };
    render() {
        return (
            <View>
                {
                    this.state.customers.map((item, index) => (
                        <TouchableOpacity
                            key = {item.id}
                            style = {styles.container}
                            onPress = {() => this.alertItemName(item)}>
                            <Text style = {styles.text}>
                                {item.name}
                                {item.make}
                                {item.model}
                                {item.color}
                            </Text>
                        </TouchableOpacity>
                    ))
                }
            </View>
        )
    }
}
export default List
